version: '3'

services:
  mosquitto:
    image: dockerfile
    depends_on:
      - nodejs
   

    ports:
      - 1883:1883

  nodejs:
    image: node:latest
    volumes:
      - "./app:/src/app "
    command: >
      bash -c "cd /src/app && npm install && node index.js"
    build: "./MQTT"
    ports:
      - 8000:8000
    